### ISSUE TITLE
train_online RuntimeError

### ISSUE THREAD

**Issue by chris-clem** [kmaninis/OSVOS-PyTorch#32]
Hi,

since today, I get the following RuntimeError after running `python train_online.py`:
```
Constructing OSVOS architecture..
Initializing weights..
Done initializing train_seqs Dataset
Done initializing val_seqs Dataset
Start of Online Training, sequence: blackswan
Traceback (most recent call last):
  File "train_online.py", line 124, in <module>
    outputs = net.forward(inputs)
  File "/home/christoph/OSVOS-PyTorch/networks/vgg_osvos.py", line 61, in forward
    x = self.stages[0](x)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 1, 3, 1] to have 3 channels, but got 1 channels instead
```

Do you know what could be the problem?

Best
Christoph

**Comment by shlokshah** [comment]
Hey Christoph,
Have you found any solution to this issue? I'm facing the same problem while running the code.
Thanks,
Shlok.
